//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ProdName { get; set; }
        public string SupplierDate { get; set; }
        public int ProdQuantity { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
